### ISSUE TITLE
First push

### ISSUE THREAD

**Issue by 4kimov** [sqids/sqids-javascript#1]
Hey @niieani, I made a good mess in this repo (out of all the awesomeness you have going on in https://github.com/niieani/hashids.js)

A few notes:
- Tests have been replaced with those from the spec (maybe we should copy over your custom ones too?)
- I did not copy over `src/tests/tests-mjs` (mostly because I don't know what they are)
- I'll copy over the basic README (like [the one Go has](https://github.com/sqids/sqids-go)), but we should also copy over a lot of the details you have in the original README
- For tests I kept vitest in there (should we use something else?)

Do you think you could take a look when you get a chance so this can become a proper repo? In the meantime, I'm still cleaning up random bits and pieces.

**Comment by 4kimov** [comment]
@niieani Tests are passing now locally 👍

**Comment by niieani** [comment]
Hi @4kimov! I’m on vacation for the next 2 weeks, but I’ll take a look after I come back.

**Comment by 4kimov** [comment]
@niieani Great! Thanks for pinging & enjoy your vacation!

**Comment by andersonjoseph** [comment]
Hello! Quick question: Does this means that [hashids](https://www.npmjs.com/package/hashids) will be archived/deprecated or something like that in favor of sqids-javascript?

I just released a fastify plugin: [fastify-hashids](https://www.npmjs.com/package/fastify-hashids) that allows users to integrate hashids in their http routes. So I wanted to know if I need to do the same with my package and maybe release a sqids version 😄

**Comment by 4kimov** [comment]
Hi @andersonjoseph, Sqids does have its own package (even tho it's not ready yet) and the algorithm does differ, so yes - creating two packages (one for Hashids and one for Sqids) does sound reasonable.

**Comment by 4kimov** [comment]
@niieani From what I can tell, this code/tests are ready to go, just need to package it up properly 👍

**Comment by niieani** [comment]
@4kimov can you give me maintainer permissions to this repo? I can't verify what GH Actions secrets are set otherwise.
We need a valid NPM_TOKEN set to publish the package to NPM.

**Comment by 4kimov** [comment]
@niieani Bumped you up to admin.

**Comment by niieani** [comment]
Okay, fixed! 
1.0.0 was auto-released.
I haven't reviewed the code yet due to time constraints, but I fixed the CI / CD + releasing process.

**Comment by 4kimov** [comment]
@niieani Ok thanks, the other libs are still pre-production, but that's ok I guess we can't unpublish 1.0.0. I'll remove the notice in the README that says this is not for production.
