### ISSUE TITLE
Sqids does not support Node.js >= 16

### ISSUE THREAD

**Issue by PCOffline** [sqids/sqids-javascript#12]
When running the following code with Node.js 16, an error occurs:
```js
const Sqids = require("sqids").default;

const sqids = new Sqids({ minLength: 6 });
```

The error has the following stack-trace:
```
ReferenceError: Blob is not defined
    at new Sqids (node_modules/sqids/cjs/sqids.js:576:9)
```
where `Blob` is being used. In Node.js 16, `Blob` is not a global object and needs to be imported using
```js
import { Blob } from 'node:buffer';
// or const { Blob } = require('node:buffer');
```

Note that the example above is using CommonJS syntax, but this issue occurs when using ES6 imports and when trying to import from `sqids/esm/sqids` as well.

**Comment by 4kimov** [comment]
Are you sure it's for _above_ as well, or are you using Node v16?

https://github.com/sqids/sqids-javascript/issues/8#issuecomment-1740923902

**Comment by PCOffline** [comment]
I'm using Node 16, but I'll check with 18 and 20

**Comment by PCOffline** [comment]
I stand corrected, the behaviour occurs only in Node 16 and 17 (in 18, the Blob module is introduced in the global scope)
