### ISSUE TITLE
Support passing in a salt for unique IDs per object type

### ISSUE THREAD

**Issue by gligorkot** [sqids/sqids-javascript#17]
It would be useful to be able to pass a salt in the Sqids config in order to generate unique ids for different salt.

Similar to hashIds for PHP feature documented here https://github.com/vinkla/hashids?tab=readme-ov-file#making-your-output-ids-unique

**Comment by 4kimov** [comment]
Just shuffle the alphabet. It has the same effect.
https://sqids.org/faq#unique
