### ISSUE TITLE
Support hex

### ISSUE THREAD

**Issue by KieronWiltshire** [sqids/sqids-javascript#22]
Please support hex

**Comment by 4kimov** [comment]
Hi @KieronWiltshire, unfortunately that's not in the plans for several reasons:

1. Hex strings are common among hashes, and Sqids should not encourage encoding or obfuscating sensitive data
1. Added complexity from having to decide how to split the hex string for encoding

However, if you have a legitimate use-case, you can always wrap the library into custom code

**Comment by KieronWiltshire** [comment]
The use case I have here is neither, I have UUIDs that I want to use in URL, but UUIDs are large and won't be consistent with other URLs.

**Comment by 4kimov** [comment]
Thanks for the feedback, makes sense. In this case, I think `#2` from above would still apply. I'll keep an open mind and see if the community demand is there as the library progresses.

In the meantime, you could try to wrap your code with these: https://github.com/niieani/hashids.js/blob/master/src/hashids.ts#L150-L190

**Comment by KieronWiltshire** [comment]
@4kimov Thanks for the suggestion, appreciate the timely response on a Sunday :)
