### ISSUE TITLE
How to check Error: Invalid ID like "https://sqids.org/playground"

### ISSUE THREAD

**Issue by amarezenebe** [sqids/sqids-javascript#26]
i try to check if i change some value still i will get result or not
for example
const sqids = new Sqids({
		alphabet: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
		minLength:11
	});

// encode
sqids.encode([1])
'UkLWZg9DAJQ'
// decode
sqids.decode('UkLWZg9DAJQ')
![image](https://github.com/sqids/sqids-javascript/assets/55350177/71304b11-f8d9-4d12-ab24-340da3d52491)

------------------------------------------------------
// the problem is when i change value from 'UkLWZg9DAJQ' to akLWZg9DAJQ still i will get value
sqids.decode('akLWZg9DAJQ')=>[368240725753862300]
BUT when i try it akLWZg9DAJQ with playground,"https://sqids.org/playground" it's give me Error: Invalid ID how can i do like playground
![image](https://github.com/sqids/sqids-javascript/assets/55350177/1896b21b-728b-43d9-96ad-1bc0d9b40a7b)

**Comment by 4kimov** [comment]
https://sqids.org/faq#valid-ids
