### ISSUE TITLE
Blocklist doesn't work as expected

### ISSUE THREAD

**Issue by yokrysty** [sqids/sqids-javascript#30]
i created a minimal example:
1234567 generates 56thj, but if i choose to block thj i expect to have another id and this does not happen
i tracked the problem to be in function isBlockedId at the first comparison:
if i change
```javascript
if (lowercaseId.length <= 3 || word.length <= 3) {
```
to
```javascript
if (lowercaseId.length === word.length) {
````
it works as expected, because it will go on the other conditions

example
```javascript
const sqids = new Sqids({
    blocklist: new Set(['thj'])
});
const id = sqids.encode([1234567]); // 56thj
console.log(id);
```

**Comment by 4kimov** [comment]
I think what you're describing has been done intentionally: https://github.com/sqids/sqids-spec/blob/main/src/index.ts#L281

Is this what you're referring to?

**Comment by yokrysty** [comment]
i'm talking about the line above of what you sent
https://github.com/sqids/sqids-spec/blob/40f407169fa0f555b93a197ff0a9e974efa9fba6/src/index.ts#L280

**Comment by yokrysty** [comment]
i'm sad that you don't plan to fix it, since it is an issue
i'm leaving here a hacky fix that i use, if anyone else needs it:
```javascript
import Sqids from 'sqids';

Sqids.prototype.isBlockedId = function (id) {
    const charReplacements = {
        '0': 'O',
        '1': 'I',
        '2': 'Z',
        '3': 'E',
        '4': 'A',
        '5': 'S',
        '7': 'T',
        '8': 'B',
        '9': 'G',
    };
    const lowercaseId = id.toLowerCase();
    let transformedId = '';
    for (let i = 0; i < lowercaseId.length; i++) {
        const chr = lowercaseId[i];
        transformedId += charReplacements[chr] || chr;
    }
    for (const word of this.blocklist) {
        if (transformedId.length === word.length) {
            return transformedId === word;
        }
        if (transformedId.includes(word)) {
            return true;
        }
    }
    return false;
};
```
