### ISSUE TITLE
When the alphabet consists only of numbers, can we provide an option to specify whether the generated IDs can start with a zero?

### ISSUE THREAD

**Issue by locene** [sqids/sqids-javascript#31]
This way, the generated IDs can be stored as an integer data type in various scenarios, such as databases.

If you're interested, I can submit a PR.

**Comment by 4kimov** [comment]
Thanks for the suggestion, but [the spec](https://github.com/sqids/sqids-spec) tries to be unopinionated about the alphabet. In dbs, ids should probably always be stored as strings, even if alphabet is numeric only.
