### ISSUE TITLE
Output from hashids and sqids for the same input is different

### ISSUE THREAD

**Issue by sduduzog** [sqids/sqids-javascript#6]
To repro: https://stackblitz.com/edit/node-q4xnc5?file=index.mjs

I'm considering migrating from hashids to sqids but I don't know how to, if the output is different. I use hashids to generate urls and this will break existing ones

**Comment by 4kimov** [comment]
You could try one of these two:

1. If your existing Hashids IDs are up to length 6, use `minLength: 7` for Sqids, that was you know how to distinguish which is which
2. Manually prefix a new character to all new Sqids IDs, that is not part of the alphabet of Hashids

**Comment by sduduzog** [comment]
Ah yes, I can use the packages side to side. I'll try figure out a way to annotate the endoder type
