### ISSUE TITLE
ReferenceError: Blob is not defined (NodeJS 16)

### ISSUE THREAD

**Issue by Toilal** [sqids/sqids-javascript#8]
It doesn't run in NodeJS, because `Blob` is used globally without being imported.

```
/home/toilal/projects/pysae/driver/node_modules/sqids/src/sqids.ts:584
    if (new Blob([alphabet]).size !== alphabet.length) {
    ^

ReferenceError: Blob is not defined
    at Sqids (/home/toilal/projects/pysae/driver/node_modules/sqids/src/sqids.ts:584:5)
   ...
```

**Comment by 4kimov** [comment]
Was just about to ask what Node version, I see - v16.

Yeah, we don't test for v16 in Github Actions. Looks like the EOL for it is in about 18 days: https://github.com/nodejs/release#end-of-life-releases
